[theme]
primaryColor="#7393B3"              # أزرق هادئ
backgroundColor="#0c1020"           # خلفية ليلية داكنة
secondaryBackgroundColor="#1a1f33"  # طبقة داكنة ناعمة
textColor="#ffffff"                 # أبيض مريح للعين
font="sans serif"
